model:
  name: 'resnet50'
  pretrained: True
  final_pooling: None #'gem'

data:
  type: 'image'
  root: 'reid-data'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  batch_size: 128
  combineall: False
  transforms: ['random_flip', 'random_crop']
  save_dir: 'log/resnet50_market1501_softmax'

loss:
  name: 'proxyAware'
  proxyAware:
    margin: 0.1
    alpha: 32
  softmax:
    label_smooth: True

train:
  optim: 'adam'
  lr: 0.001
  max_epoch: 100
  fixbase_epoch: 10
  open_layers: ['classifier']
  lr_scheduler: 
    name: 'single_step'
    stepsize: 40
    gamma: 0.1
    max_epoch: 1
    T_0: 5 #starts after certain epochs # Cosine Warm restarts
    eta_min: 1e-6 # Cosine Warm restarts


test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False

custom:
  custom_layers: []
    # ArcFaceMarginProduct:
    #   s: 30.0
    #   m: 0.50
    #   easy_margin: False
    #   ls_eps: 0.0

wandb:
  project: "REID-V3"
  entity: "tangoeye"